name: sphene

services:
  mta:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - ./sphene:/app/server/mods/deathmatch/resources/sphene
      - ./sphene-interface:/app/server/mods/deathmatch/resources/sphene-interface
      - ./docker/development/mta/mtaserver.conf:/app/server/mods/deathmatch/mtaserver.conf
      - ./docker/development/mta/acl.xml:/app/server/mods/deathmatch/acl.xml
      - ./vendor/scripts:/app/server/mods/deathmatch/resources/[vendor]
      - resource-cache:/app/server/mods/deathmatch/resource-cache/http-client-files
      - internal-databases:/app/server/mods/deathmatch/databases
      - registry-database:/app/server/mods/deathmatch/registry.db
    ports:
      - '${MTA_SERVER_PORT:-22003}:22003/udp'
      - '${MTA_HTTP_PORT:-22005}:22005/tcp'
      - '22126:22126/udp'
    networks:
      - sphene
  nginx:
    extends:
      file: ./sphene-api/docker-compose.yml
      service: nginx
    image: nginx:1.23-alpine
    volumes:
      - resource-cache:/var/www/http-client-files:ro
      - ./docker/development/nginx/conf.d/mta.conf.template:/etc/nginx/templates/mta.conf.template:ro
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - MTA_HTTP_PORT=${MTA_HTTP_PORT:-32003}
    ports:
      - ${MTA_HTTP_PORT:-32003}:${MTA_HTTP_PORT:-32003}
    networks:
      - sphene
  api:
    extends:
      file: ./sphene-api/docker-compose.yml
      service: api
    networks:
      - sphene
  mysql:
    extends:
      file: ./sphene-api/docker-compose.yml
      service: mysql
    networks:
      - sphene
  phpmyadmin:
    extends:
      file: ./sphene-api/docker-compose.yml
      service: phpmyadmin
    networks:
      - sphene
networks:
  sphene:
    driver: bridge
volumes:
  resource-cache:
  internal-databases:
  registry-database:
  sphene-mysql:
    driver: local