-----------------------------------
-- * Variables
-----------------------------------

TaskCode = {}
TaskCode.__index = TaskCode

TaskCode.DESTROY_ELEMENT = 0xF00
TaskCode.ELEMENT_SET_INTERIOR = 0xA50
TaskCode.ELEMENT_SET_POSITION = 0xA51
TaskCode.ELEMENT_SET_ROTATION = 0xA52

TaskCode.EXPLODE_VEHICLE = 0xD00
TaskCode.DESTROY_VEHICLE = TaskCode.DESTROY_ELEMENT

TaskCode.CREATE_ACTOR = 0xB00
TaskCode.GIVE_PLAYER_MONEY = 0xB01
TaskCode.GIVE_ACTOR_JETPACK = 0xB02
TaskCode.REMOVE_ACTOR_JETPACK = 0xB03
TaskCode.GIVE_WEAPON = 0xB10
TaskCode.REMOVE_WEAPON = 0xB11
TaskCode.SET_WEAPONS_HIDDEN = 0xB1F
TaskCode.WARP_INTO_VEHICLE = 0xB20
TaskCode.REMOVE_FROM_VEHICLE = 0xB21
TaskCode.PLAYER_SET_WANTED_LEVEL = 0xB30
TaskCode.ACTOR_KILL = 0xB60
TaskCode.DESTROY_ACTOR = TaskCode.DESTROY_ELEMENT

TaskCode.SYNC_CAMERA_INTERIOR = 0xF01

TaskCode.ACTOR_SYNC = 0x001

TaskCode.LOAD_ELEMENT = 0xA00
TaskCode.UNLOAD_ELEMENT = 0xA01
TaskCode.ELEMENT_SYNC = 0xA02

TaskCode.PLAYER_ADD_TO_VEHICLE = 0xC00
TaskCode.PLAYER_REMOVE_FROM_VEHICLE = 0xC01